name: Next DevOps Pipeline

trigger:
    branches:
      include:
        - main

pool:
  vmImage: ubuntu-latest

pr: none

variables:
  SENTRY_AUTH_TOKEN: 
    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

stages:
  
  
  - stage: prepare
    displayName: "Prepare"
    jobs:
      - job: prepare_build_tools
        displayName: "Prepare build tools"
        steps:
          - task:  NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
          
          - task: Npm@1
            displayName: 'Install NPM'
  
  - stage: build
    displayName: "Build"
    jobs:
      - job: install
        displayName: "NPM Install"
        steps:
          - script: 
              npm ci
              echo $SENTRY_AUTH_TOKEN