name: Next DevOps Pipeline

trigger:
    branches:
      include:
        - main

pool:
  vmImage: ubuntu-latest

pr: [main]

variables:
  SENTRY_AUTH_TOKEN: 
    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

stages:
  
  
  - stage: build
    displayName: "Build"
    jobs:
      - job: Build
        displayName: "Build"
        steps:
          - task:  NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'
          
          - script: |
              npm ci
              npm run build
              echo 'Sentry Auth Token $SENTRY_AUTH_TOKEN'